# Generated by Django 6.0.3 on 2026-03-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('A', 'Assistido'), ('N', 'Não Assistido')], default='N', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
